Final changes: Support for local/remote mirrors. New config file option to specify which mirrors should be used. The README file has details.

diff --git a/files/rkhunter b/files/rkhunter
--- a/files/rkhunter
+++ b/files/rkhunter
@@ -2512,6 +2512,27 @@ get_mirror_options() {
 		fi
 	fi
 
+
+	#
+	# Finally, we see which mirrors are to be used.
+	#
+
+	MIRRORS_MODE=`grep '^MIRRORS_MODE=' ${CONFIGFILE} | tail -1`
+
+	if [ -n "${MIRRORS_MODE}" ]; then
+		MIRRORS_MODE=`echo "${MIRRORS_MODE}" | sed -e 's/MIRRORS_MODE=//' | tr -d '"' | tr -s ' '`
+
+		if [ -z "${MIRRORS_MODE}" -o "${MIRRORS_MODE}" = " " ]; then
+			echo "Invalid MIRRORS_MODE configuration option - no value specified."
+			exit 1
+		elif [ "${MIRRORS_MODE}" != "0" -a "${MIRRORS_MODE}" != "1" -a "${MIRRORS_MODE}" != "2" ]; then
+			echo "Invalid MIRRORS_MODE configuration option: ${MIRRORS_MODE}"
+			exit 1
+		fi
+	else
+		MIRRORS_MODE=0
+	fi
+
 	return
 }
 
@@ -3112,7 +3133,13 @@ get_next_mirror() {
 	# Return if there are no defined mirrors.
 	#
 
-	MIRROR=`egrep -i '^(remote|mirror)=' ${DB_PATH}/mirrors.dat | head -n 1`
+	if [ $MIRRORS_MODE -eq 0 ]; then
+		MIRROR=`egrep -i '^(local|remote|mirror)=' ${DB_PATH}/mirrors.dat | head -n 1`
+	elif [ $MIRRORS_MODE -eq 1 ]; then
+		MIRROR=`grep -i '^local=' ${DB_PATH}/mirrors.dat | head -n 1`
+	elif [ $MIRRORS_MODE -eq 2 ]; then
+		MIRROR=`grep -i '^remote=' ${DB_PATH}/mirrors.dat | head -n 1`
+	fi
 
 	if [ -z "${MIRROR}" ]; then
 		display --to LOG --type INFO MIRRORS_NO_MIRRORS "${DB_PATH}/mirrors.dat"
@@ -3127,7 +3154,14 @@ get_next_mirror() {
 
 	if [ $ROTATE_MIRRORS -eq 0 ]; then
 		N=`expr $TOTAL_MIRRORS - $MIRROR_COUNT`
-		MIRROR=`egrep -i '^(remote|mirror)=' ${DB_PATH}/mirrors.dat | head -n $N | tail -1 | cut -d= -f2-`
+
+		if [ $MIRRORS_MODE -eq 0 ]; then
+			MIRROR=`egrep -i '^(local|remote|mirror)=' ${DB_PATH}/mirrors.dat | head -n $N | tail -1 | cut -d= -f2-`
+		elif [ $MIRRORS_MODE -eq 1 ]; then
+			MIRROR=`grep -i '^local=' ${DB_PATH}/mirrors.dat | head -n $N | tail -1 | cut -d= -f2-`
+		elif [ $MIRRORS_MODE -eq 2 ]; then
+			MIRROR=`grep -i '^remote=' ${DB_PATH}/mirrors.dat | head -n $N | tail -1 | cut -d= -f2-`
+		fi
 
 		return
 	fi
@@ -3152,7 +3186,7 @@ get_next_mirror() {
 	# Next get the remaining mirrors.
 	#
 
-	OTHERMIRRORS=`egrep -i '^(remote|mirror)=' ${DB_PATH}/mirrors.dat | grep -v "${MIRROR}"`
+	OTHERMIRRORS=`egrep -i '^(local|remote|mirror)=' ${DB_PATH}/mirrors.dat | grep -v "^${MIRROR}\$"`
 
 
 	#
@@ -3197,8 +3231,14 @@ get_next_mirror() {
 
 download_file() {
 
+	#
 	# This function downloads a specified file. It takes three parameters:
 	#     1=mirror, 2=url, 3=output file
+	#
+	# The URL is just the filename portion. The user will supply the
+	# full URL, less the filename, to where the files are stored on
+	# the local or remote server. For the SourceForge mirrors we will
+	# provide the URL.
 	#
 	# The function sets a return code (DNLOADERR).
 	#
@@ -3221,7 +3261,19 @@ download_file() {
 	TOTAL_MIRRORS=0
 
 	if [ -f "${DB_PATH}/mirrors.dat" ]; then
-		MIRROR_COUNT=`egrep -i '^(remote|mirror)=' ${DB_PATH}/mirrors.dat | wc -l | tr -d ' '`
+		#
+		# The version check will use both the
+		# SF mirrors and remote mirrors.
+		#
+
+		if [ $MIRRORS_MODE -eq 0 ]; then
+			MIRROR_COUNT=`egrep -i '^(local|remote|mirror)=' ${DB_PATH}/mirrors.dat | wc -l | tr -d ' '`
+		elif [ $MIRRORS_MODE -eq 1 ]; then
+			MIRROR_COUNT=`grep -i '^local=' ${DB_PATH}/mirrors.dat | wc -l | tr -d ' '`
+		elif [ $MIRRORS_MODE -eq 2 ]; then
+			MIRROR_COUNT=`grep -i '^remote=' ${DB_PATH}/mirrors.dat | wc -l | tr -d ' '`
+		fi
+
 		test -z "${MIRROR_COUNT}" && MIRROR_COUNT=0
 	fi
 
@@ -3235,7 +3287,26 @@ download_file() {
 
 		if [ -z "${MIRROR}" ]; then
 			get_next_mirror
-			test -z "${MIRROR}" && MIRROR="http://rkhunter.sourceforge.net"
+
+			if [ -z "${MIRROR}" ]; then
+				if [ $MIRRORS_MODE -eq 0 ]; then
+					MIRROR="http://rkhunter.sourceforge.net"
+					display --to LOG --type INFO MIRRORS_SF_DEFAULT "${MIRROR}"
+				else
+					DNLOADERR=1
+					break
+				fi
+			fi
+
+
+			#
+			# For the SF mirrors add on the final
+			# part of the mirror URL.
+			#
+
+			if [ "${MIRROR}" = "http://rkhunter.sourceforge.net" ]; then
+				MIRROR="${MIRROR}/1.3"
+			fi
 		fi
 
 
@@ -3338,7 +3409,7 @@ do_i18n_update() {
 	# number against the installed file.
 	#
 
-	download_file "${MIRROR}" "/1.3/i18n/i18n.ver" "${RKHUPD_FILE}"
+	download_file "${MIRROR}" "/i18n/i18n.ver" "${RKHUPD_FILE}"
 
 	if [ $? -eq 0 ]; then
 		#
@@ -3396,7 +3467,7 @@ do_i18n_update() {
 
 
 			if [ $PROG_VERS -lt $LATEST_VERS ]; then
-				download_file "${MIRROR}" "/1.3/i18n/${LANGFILE}" "${RKHUPD_FILE}"
+				download_file "${MIRROR}" "/i18n/${LANGFILE}" "${RKHUPD_FILE}"
 
 				if [ $? -eq 0 ]; then
 					test $RET_CODE -eq 0 && RET_CODE=2
@@ -3508,7 +3579,7 @@ do_update() {
 		# previous versions do not use.
 		#
 
-		download_file "${MIRROR}" "/1.3/${UPDFILE}" "${RKHUPD_FILE}"
+		download_file "${MIRROR}" "/${UPDFILE}" "${RKHUPD_FILE}"
 
 
 		#
@@ -3617,21 +3688,11 @@ do_versioncheck() {
 
 
 	#
-	# The URL for the latest version is static. There is no need
-	# for a user to change it or to distribute new versions from
-	# anywhere other than SourceForge. Besides which it would
-	# mess up the download stats :-)
-	#
-
-	URL="/rkhunter_latest.dat"
-
-
-	#
 	# Download the file, and then compare the current value
 	# with the downloaded one.
 	#
 
-	download_file "${MIRROR}" "${URL}" "${RKHVC_FILE}"
+	download_file "${MIRROR}" "/rkhunter_latest.dat" "${RKHVC_FILE}"
 
 	if [ $? -eq 0 ]; then
 		LATESTVERSION=`cat ${RKHVC_FILE} 2>/dev/null`
@@ -10835,8 +10896,11 @@ RKHLANGUPDT=0
 
 # By default we rotate the mirrors in the mirrors.dat file,
 # and we update the file when the '--update' option is used.
+# The default MIRRORS_MODE is set such that we use both local
+# and remote mirrors.
 ROTATE_MIRRORS=1
 UPDATE_MIRRORS=1
+MIRRORS_MODE=0
 
 
 ######################################################################
@@ -11880,6 +11944,14 @@ if [ $UPDATE -eq 1 -o $VERSIONCHECK -eq 1 ]; then
 		display --to LOG --type INFO CONFIG_NO_ROTATE_MIRRORS
 	else
 		display --to LOG --type INFO CONFIG_ROTATE_MIRRORS
+	fi
+
+	if [ $MIRRORS_MODE -eq 0 ]; then
+		display --to LOG --type INFO CONFIG_MIRRORS_MODE0
+	elif [ $MIRRORS_MODE -eq 1 ]; then
+		display --to LOG --type INFO CONFIG_MIRRORS_MODE1
+	else
+		display --to LOG --type INFO CONFIG_MIRRORS_MODE2
 	fi
 
 	if [ $UPDATE -eq 1 ]; then
