Final changes for the BSD package manager. Tested with later systems - NetBSD should use 'BSD', FreeBSD can use either 'BSD' or 'BSDng', OpenBSD does not seem to work. (It provides a base64 encoded SHA-256 value.) DragonflyBSD (untested) seems to be the same as FreeBSD.

diff --git a/files/rkhunter b/files/rkhunter
--- a/files/rkhunter
+++ b/files/rkhunter
@@ -4468,7 +4468,7 @@ get_sha_hash_function() {
 
 	SHA_SIZE=$1
 
-	check_is_digit SHA_SIZE HASH_FUNC ANY1
+	check_is_digit SHA_SIZE HASH_CMD ANY1
 
 	if [ $ERRCODE -eq 1 ]; then
 		echo "Error: Invalid argument to get_sha_hash_function function: $*" >&2
@@ -4643,7 +4643,7 @@ get_hash_function() {
 		if [ $HASH_OPT -eq 1 ]; then
 			echo "Invalid '--hash' option: no usable hash command or perl module for MD5 could be found."
 		else
-			echo "Invalid HASH_FUNC configuration option: no usable hash command or perl module for MD5 could be found."
+			echo "Invalid HASH_CMD configuration option: no usable hash command or perl module for MD5 could be found."
 		fi
 	elif [ "${HASH_FUNC}" = "RIPEMD160" -o "${HASH_FUNC}" = "WHIRLPOOL" ]; then
 		LEAVE=1
@@ -4651,7 +4651,7 @@ get_hash_function() {
 		if [ $HASH_OPT -eq 1 ]; then
 			echo "Invalid '--hash' option: no perl module for ${HASH_FUNC} could be found."
 		else
-			echo "Invalid HASH_FUNC configuration option: no perl module for ${HASH_FUNC} could be found."
+			echo "Invalid HASH_CMD configuration option: no perl module for ${HASH_FUNC} could be found."
 		fi
 	elif [ -n "${HASH_FUNC}" ]; then
 		HASH_CMD=`echo "${HASH_FUNC}" | cut -d' ' -f1`
@@ -4674,17 +4674,17 @@ get_hash_function() {
 			echo "Invalid '--hash' option: command is non-existent or not executable: ${HASH_CMD}"
 		else
 			LEAVE=1
-			echo "Invalid HASH_FUNC configuration option: command is non-existent or not executable: ${HASH_CMD}"
+			echo "Invalid HASH_CMD configuration option: command is non-existent or not executable: ${HASH_CMD}"
 		fi
 	elif [ $HASH_OPT -eq 1 ]; then
 		LEAVE=1
 		echo "Invalid '--hash' option: no usable hash command or perl module could be found."
 	elif [ $SHA_SIZE -ge 1 ]; then
 		LEAVE=1
-		echo "Invalid HASH_FUNC configuration option: no usable hash command or perl module for SHA${SHA_SIZE} could be found."
+		echo "Invalid HASH_CMD configuration option: no usable hash command or perl module for SHA${SHA_SIZE} could be found."
 	else
 		LEAVE=1
-		echo "Invalid HASH_FUNC configuration option: no usable hash command or perl module could be found."
+		echo "Invalid HASH_CMD configuration option: no usable hash command or perl module could be found."
 	fi
 
 
@@ -4803,7 +4803,6 @@ get_hash_function() {
 			fi
 		fi
 
-#jh
 		if [ $CHECK -eq 1 -o $PROP_UPDATE -eq 1 -o $CONFIG_CHECK -eq 1 ]; then
 			PKGMGR_SHA_HASH=`get_sha_hash_function 256`
 
@@ -6459,36 +6458,28 @@ ${DIR}:1"
 			fi
 			;;
 		BSD)
-#jh - add --uninstall option as alias for remove to installer script
-#jh - pkg_info -F does not exist in FreeBSd - modify code. Also check for dragonfly openbsd etc.
-#jh - use '-W' or '-L' instead?
 			#
 			# First see if the file is exempt or part of a known package.
 			#
 
-			if [ $NOVRFYFILE -eq 1 ]; then
-				ERRCODE=1
-			else
+			PKGNAME=""
+
+			if [ $NOVRFYFILE -eq 0 ]; then
 				RKHTMPVAR=`${PKG_CMD} -F -e "${FNAME}" 2>/dev/null`
 				ERRCODE=$?
-			fi
 
-			if [ $ERRCODE -eq 0 ]; then
-				#
-				# Now we sort out the base part of the package name.
-				#
+				if [ $ERRCODE -ne 0 ]; then
+					#
+					# It may be that we need to use the '-W' option instead.
+					#
 
-				PKGNAME=`echo "${RKHTMPVAR}" | tail ${TAIL_OPT}1 | sed -e 's/[0-9]nb[0-9][0-9]*$//; s/-[0-9.]*$//'`
-			elif [ $NOVRFYFILE -eq 0 ]; then
-#jhjh
-				#
-				# It may be that we need to use the '-W' option instead.
-				#
+					RKHTMPVAR=`${PKG_CMD} -q -W "${FNAME}" 2>/dev/null`
+					ERRCODE=$?
+				fi
 
-				RKHTMPVAR=`${PKG_CMD} -q -W "${FNAME}" 2>/dev/null`
-				ERRCODE=$?
-
-				test $ERRCODE -eq 0 && PKGNAME=`echo "${RKHTMPVAR}" | tail ${TAIL_OPT}1`
+				if [ $ERRCODE -eq 0 -a -n "${RKHTMPVAR}" ]; then
+					PKGNAME=`echo "${RKHTMPVAR}" | tail ${TAIL_OPT}1`
+				fi
 			fi
 			;;
 		BSDNG)
@@ -6587,7 +6578,6 @@ ${DIR}:1"
 					#
 
 					if [ -n "${PKGNAME}" ]; then
-#jhjh
 						FILNAM=`echo "${FNAME}" | sed -e 's:^/usr/pkg/::; s:^/usr/local/::; s:\.:\\\.:g'`
 						SYSHASH=`${PKG_CMD} -v -L "${PKGNAME}" 2>/dev/null | grep -A 1 "File: ${FILNAM}\$" 2>/dev/null | tail ${TAIL_OPT}1 | cut -d: -f3`
 						test -n "${SYSHASH}" && FILE_IS_PKGD=1
@@ -6883,7 +6873,6 @@ do_prop_update() {
 	if [ -n "${RELEASE}" ]; then
 		display --to LOG --type INFO PROPUPD_REL_FILE "${RELEASE}"
 	else
-#jh
 		RKHTMPVAR=`ls -ld /etc/*release* /etc/*version* 2>/dev/null | tr '\n' ' '`
 
 		if [ -n "${RKHTMPVAR}" ]; then
@@ -10720,7 +10709,6 @@ ${RKHLINE}"
 					PKGNAME=""
 
 					if [ $NOVRFYFILE -eq 0 ]; then
-#jhjh
 						RKHTMPVAR=`${PKG_CMD} -F -e "${FNAME}" 2>/dev/null`
 						ERRCODE=$?
 
@@ -10733,7 +10721,9 @@ ${RKHLINE}"
 							ERRCODE=$?
 						fi
 
-						test $ERRCODE -eq 0 && PKGNAME=`echo "${RKHTMPVAR}" | tail ${TAIL_OPT}1`
+						if [ $ERRCODE -eq 0 -a -n "${RKHTMPVAR}" ]; then
+							PKGNAME=`echo "${RKHTMPVAR}" | tail ${TAIL_OPT}1`
+						fi
 					fi
 
 					if [ -n "${PKGNAME}" ]; then
@@ -10742,7 +10732,6 @@ ${RKHLINE}"
 						# pathname, and then get the hash value.
 						#
 
-#jhjh
 						FNGREP=`echo "${FNAMEGREP}" | sed -e 's:^/usr/pkg/::; s:^/usr/local/::'`
 
 						SYSHASH=`${PKG_CMD} -v -L "${PKGNAME}" 2>/dev/null | grep -A 1 "File: ${FNGREP}\$" 2>/dev/null | tail ${TAIL_OPT}1 | cut -d: -f3`
