Suspscan bug and minor changes.

diff --git a/files/rkhunter b/files/rkhunter
--- a/files/rkhunter
+++ b/files/rkhunter
@@ -495,7 +495,7 @@ suckit_extra_checks() {
 
 	#
 	# The first check tests the link count of the /sbin/init file.
-	# We use the NLINKs variable to indicate the test result:
+	# We use the NLINKS variable to indicate the test result:
 	#	-1 means that no stat command was available
 	#	 0 means that the stat command gave an error
 	#	 1 is okay
@@ -5101,14 +5101,6 @@ suspscan() {
 	# - Exclude OSes?
 	# - Check config defaults. If one is missing, don't run.
 
-
-	#
-	# We can only run this on Linux for the moment.
-	#
-
-	test "${OPERATING_SYSTEM}" != "Linux" && return
-
-
 	if ! `check_test suspscan`; then
 		display --to LOG --type INFO --nl USER_DISABLED_TEST suspscan
 		return
@@ -5124,10 +5116,6 @@ suspscan() {
 	if [ -z "${FILE_CMD}" ]; then
 		display --to SCREEN+LOG --type PLAIN --result SKIPPED --color YELLOW --screen-indent 4 SUSPSCAN_CHECK
 		display --to LOG --type INFO NOT_FOUND_CMD "file"
-		return
-	elif [ -z "${STAT_CMD}" ]; then
-		display --to SCREEN+LOG --type PLAIN --result SKIPPED --color YELLOW --screen-indent 4 SUSPSCAN_CHECK
-		display --to LOG --type INFO NOT_FOUND_CMD "stat"
 		return
 	elif [ -z "${STRINGS_CMD}" ]; then
 		display --to SCREEN+LOG --type PLAIN --result SKIPPED --color YELLOW --screen-indent 4 SUSPSCAN_CHECK
@@ -5212,6 +5200,9 @@ suspscan() {
 
 	FOUND=0
 	FOUNDDIRS=""
+	FILENAME="${SUSPSCAN_TEMP}/suspscan.$$.strings"
+
+	rm -f ${SUSPSCAN_TEMP}/suspscan.$$.strings >/dev/null 2>&1
 
 	for SUSPSCAN_DIR in $SUSPSCAN_DIRS ; do
 		if [ -d "${SUSPSCAN_DIR}" ]; then
@@ -5221,85 +5212,83 @@ suspscan() {
 				display --to LOG --type PLAIN --log-indent 4 SUSPSCAN_DIR_CHECK "${SUSPSCAN_DIR}"
 			fi
 
-# jh			$FIND_CMD "${SUSPSCAN_DIR}" ! -type d | while read SUSPSCAN_ITEM; do
-			for SUSPSCAN_ITEM in `$FIND_CMD "${SUSPSCAN_DIR}" ! -type d`; do
-				SUSPSCAN_TYPE=`$STAT_CMD -c %F "${SUSPSCAN_ITEM}" | tr '[A-Z]' '[a-z]'`
-				SUSPSCAN_SIZE=`$STAT_CMD -c %s "${SUSPSCAN_ITEM}"`
+			for SUSPSCAN_ITEM in `$FIND_CMD "${SUSPSCAN_DIR}" -type f -a ! -type l -a -size -${SUSPSCAN_MAXSIZE}c`; do
+				test ! -s "${SUSPSCAN_ITEM}" && continue
 
-				if [ -s "${SUSPSCAN_ITEM}" -a $SUSPSCAN_SIZE -le $SUSPSCAN_MAXSIZE -a "$SUSPSCAN_TYPE" = "regular file" ]; then
-					$FILE_CMD "${SUSPSCAN_ITEM}" | cat -v | cut -d' ' -f2- | egrep -i 'execu|shell|libr' >/dev/null
-					if [ $? -eq 0 ]; then
-						FOUND=1
-						SUSPSCAN_NUM=1; SUSPSCAN_SCORE=0
+				$FILE_CMD "${SUSPSCAN_ITEM}" | cat -v | cut -d' ' -f2- | egrep -i 'execu|shell|libr' >/dev/null
+				if [ $? -eq 0 ]; then
+					FOUND=1
+					SUSPSCAN_NUM=1; SUSPSCAN_SCORE=0
 
-						$STRINGS_CMD -n 10 "${SUSPSCAN_ITEM}" >"${SUSPSCAN_TEMP}/suspscan.$$.strings" 2>&1
+					$STRINGS_CMD -n 10 "${SUSPSCAN_ITEM}" >${FILENAME} 2>&1
 
-						# Too short, need extended regex or influence relation only on these: dcc irc bot ban chan
-						# False positives: memory
-						# The list below should be broken out to a .dat file or rkhunter.conf.
+					# Too short, need extended regex or influence relation only on these: dcc irc bot ban chan
+					# False positives: memory
+					# The list below should be broken out to a .dat file or rkhunter.conf.
 
-						for SUSPSCAN_STRING in a:0x..,.0x.., a:add?  a:asm a:%:bh a:decb a:decl a:disasm a:%e[bp,di,sp] a:%e[cx,si] a:%e?x a:%hi a:inc[b,l] a:jmp a:jmpcode ajuda a:jump a:%?l a:mov?  a:nasm a:ndisasm a:nopsize a:notb a:offset a:opcode a:p[op,ush] a:reassembl a:ret a:ro[r,l]b a:sub?  a:xor d:bonk d:flood d:jolt d:kuang d:land d:nuke d:saihyousen d:tear d:teardrop f:abort f:access f:AF_INET f:atoi@ f:buf[fe,si] f:call f:changeown f:exec.* f:fopen@ f:fread f:free f:fscanf f:loop f:lseek f:malloc f:memcpy f:memset f:mmap f:putenv f:static.char.*= f:str[len,cat] f:'system(' i:botz i:bounc i:dalnet i:dc\.pl i:eggbot i:eggshell i:invite i:irc\.  i:iroffer i:nick i:pbsync i:psybnc i:vhost i:xdcc n:bind n:connect n:'connect(' n:'gethostbyname(' n:'getprotobyname(' n:ident n:inet n:'inet_aton(' n:IO::Socket n:listen n:network n:packet n:relay n:remote n:resolv n:rhost n:sendfile n:server n:setsockopt n:'(?sock' n:sockaddr n:'sockaddr_in(' n:sock[ad,et,fd] n:'socket(' n:'socket@' n:socketcall n:socklen n:'sockopen(' s:?0x[a-z0-9]\{2\}.* s:backdoor s:/bin/sh s:chmod s:chown s:keylog s:logcleaner s:login s:password s:/ptmx s:/pty s:setgid s:setreuid s:setuid s:shellcode s:tmp/sh s:/tty s:\"/\x[a-z0-9]\{2\}.* t:'0^wN' t:0wn3d t:0wned t:advantag t:advisory t:affect t:allocation t:anony t:arbitr t:attack t:authenti t:bogus t:brute t:buscar t:comando t:crypt t:decode t:destinat t:destruct t:device t:/dev/kmem t:/dev/mem t:disclosure t:discover t:distrib t:downloader t:elf-init t:elflbl t:endian t:enem t:evasion t:exception t:exclusiv t:existant t:exploit t:fake t:fatal t:fixed t:fragment t:fuckin t:group t:h[a4]x[oO0]r t:hardcod t:harvest t:heap t:hexdump t:hidden t:hide t:host t:hostile t:hotfix t:infect t:info t:init t:inject t:kernel t:kill t:leak t:'log(' t:mech t:modif[yi] t:mprotect t:nvalid t:overwrit t:pages t:patch t:payload t:philar\.pl t:pointer t:priv[a8] t:process t:procur t:publi[cs] t:purpose t:registered t:risk t:r.nin t:sapphire t:scam t:segment t:sent t:shell.php t:signed t:sniff t:spawn t:spoof t:stealth t:succes t:suficiente t:terminate t:transact t:transpar t:udp.pl t:victim t:violat t:vma t:vuln t:worm t:wreck v:aleph v:OpticFiber x:apache x:mambo x:openssl x:samba x:sshd x:wwwadmin ; do
+					for SUSPSCAN_STRING in a:0x..,.0x.., a:add? a:asm a:%:bh a:decb a:decl a:disasm a:%e[bp,di,sp] a:%e[cx,si] a:%e?x a:%hi a:inc[b,l] a:jmp a:jmpcode ajuda a:jump a:%?l a:mov? a:nasm a:ndisasm a:nopsize a:notb a:offset a:opcode a:p[op,ush] a:reassembl a:ret a:ro[r,l]b a:sub? a:xor d:bonk d:flood d:jolt d:kuang d:land d:nuke d:saihyousen d:tear d:teardrop f:abort f:access f:AF_INET f:atoi@ f:buf[fe,si] f:call f:changeown f:exec.* f:fopen@ f:fread f:free f:fscanf f:loop f:lseek f:malloc f:memcpy f:memset f:mmap f:putenv f:static.char.*= f:str[len,cat] f:'system(' i:botz i:bounc i:dalnet i:dc\.pl i:eggbot i:eggshell i:invite i:irc\. i:iroffer i:nick i:pbsync i:psybnc i:vhost i:xdcc n:bind n:connect n:'connect(' n:'gethostbyname(' n:'getprotobyname(' n:ident n:inet n:'inet_aton(' n:IO::Socket n:listen n:network n:packet n:relay n:remote n:resolv n:rhost n:sendfile n:server n:setsockopt n:'(?sock' n:sockaddr n:'sockaddr_in(' n:sock[ad,et,fd] n:'socket(' n:'socket@' n:socketcall n:socklen n:'sockopen(' s:?0x[a-z0-9]\{2\}.* s:backdoor s:/bin/sh s:chmod s:chown s:keylog s:logcleaner s:login s:password s:/ptmx s:/pty s:setgid s:setreuid s:setuid s:shellcode s:tmp/sh s:/tty s:\"/\x[a-z0-9]\{2\}.* t:'0^wN' t:0wn3d t:0wned t:advantag t:advisory t:affect t:allocation t:anony t:arbitr t:attack t:authenti t:bogus t:brute t:buscar t:comando t:crypt t:decode t:destinat t:destruct t:device t:/dev/kmem t:/dev/mem t:disclosure t:discover t:distrib t:downloader t:elf-init t:elflbl t:endian t:enem t:evasion t:exception t:exclusiv t:existant t:exploit t:fake t:fatal t:fixed t:fragment t:fuckin t:group t:h[a4]x[oO0]r t:hardcod t:harvest t:heap t:hexdump t:hidden t:hide t:host t:hostile t:hotfix t:infect t:info t:init t:inject t:kernel t:kill t:leak t:'log(' t:mech t:modif[yi] t:mprotect t:nvalid t:overwrit t:pages t:patch t:payload t:philar\.pl t:pointer t:priv[a8] t:process t:procur t:publi[cs] t:purpose t:registered t:risk t:r.nin t:sapphire t:scam t:segment t:sent t:shell\.php t:signed t:sniff t:spawn t:spoof t:stealth t:succes t:suficiente t:terminate t:transact t:transpar t:udp\.pl t:victim t:violat t:vma t:vuln t:worm t:wreck v:aleph v:OpticFiber x:apache x:mambo x:openssl x:samba x:sshd x:wwwadmin ; do
+						SUSPSCAN_TERM="${SUSPSCAN_STRING}"
+
+						#
+						# Searchterm with class
+						#
+
+						case "${SUSPSCAN_STRING}" in
+						[a-z]:*) # I mean: term=${s//*:}
+							 # Class as in asm, text, networking, IRC
+							 SUSPSCAN_CLASS=`echo "${SUSPSCAN_STRING}" | cut -d: -f1`
+							 SUSPSCAN_TERM=`echo "${SUSPSCAN_STRING}" | cut -d: -f2-`
+							 ;;
+						esac
+
+						#
+						# Searchterm with multiplier
+						#
+
+						case "${SUSPSCAN_STRING}" in
+						*+[0-9][0-9]*) # I mean: term="${s%%+*}";
+							  SUSPSCAN_TERM=`echo "${SUSPSCAN_TERM}" | cut -d'+' -f1`
+							  SUSPSCAN_MULTIPLIER=`echo "${SUSPSCAN_STRING}" | cut -d'+' -f2`
+							  ;;
+						esac
+
+						grep -i "${SUSPSCAN_TERM}" ${FILENAME} | head -n 1 >/dev/null
+						if [ $? -eq 0 ]; then
 							#
-							# Searchterm with class
+							# Use hitlist to find relationship with other terms and influence multiplier. Examples:
+							# {opcode,jmpcode} + {disclosure,privat,kernel}
+							# {bin/sh,tmp/sh} + {setuid,setgid,drop}
+							# irc + {server,nick,iroffer,?dcc}
+							# This implies the "more serious" terms need to be moved to the front of the table.
+							# We could also prefix a category along the lines of:
+							# a: (asm) e: (exploit) to help classification: e:jmp+100 e:%e[cx,si]+100
 							#
 
-							case "${SUSPSCAN_STRING}" in
-							[a-z]:*) # I mean: term=${s//*:}
-								 # Class as in asm, text, networking, IRC
-								 SUSPSCAN_CLASS=`echo "${SUSPSCAN_STRING}"|awk -F':' '{print $1}'`
-								 SUSPSCAN_TERM=`echo "${SUSPSCAN_STRING}"|awk -F':' '{print $2}'`
-								 ;;
-							esac
+							SUSPSCAN_HITS="$SUSPSCAN_NUM ${SUSPSCAN_HITS}"
 
-							#
-							# Searchterm with multiplier
-							#
-
-							case "${SUSPSCAN_STRING}" in
-							*+[0-9]*) # I mean: term="${s%%+*}";
-								  SUSPSCAN_TERM=`echo "${SUSPSCAN_STRING}"|awk -F'+' '{print $1}'`
-								  SUSPSCAN_MULTIPLIER=`echo "${SUSPSCAN_STRING}"|awk -F'+' '{print $2}'`
-								  ;;
-							esac
-
-							grep -i "${SUSPSCAN_STRING}" "${SUSPSCAN_TEMP}/suspscan.$$.strings" | head -n 1 >/dev/null
-							if [ $? -eq 0 ]; then
-								#
-								# Use hitlist to find relationship with other terms and influence multiplier. Examples:
-								# {opcode,jmpcode} + {disclosure,privat,kernel}
-								# {bin/sh,tmp/sh} + {setuid,setgid,drop}
-								# irc + {server,nick,iroffer,?dcc}
-								# This implies the "more serious" terms need to be moved to the front of the table.
-								# We could also prefix a category along the lines of:
-								# a: (asm) e: (exploit) to help classification: e:jmp+100 e:%e[cx,si]+100
-								#
-
-								SUSPSCAN_HITS="$SUSPSCAN_NUM ${SUSPSCAN_HITS}"
-
-								if [ -n "$SUSPSCAN_MULTIPLIER" ]; then
-									SUSPSCAN_SCORE=`expr ${SUSPSCAN_SCORE} + ${SUSPSCAN_MULTIPLIER}` 
-									unset SUSPSCAN_MULTIPLIER
-								else
-									SUSPSCAN_SCORE=`expr ${SUSPSCAN_SCORE} + 1`
-								fi
+							if [ -n "$SUSPSCAN_MULTIPLIER" ]; then
+								SUSPSCAN_SCORE=`expr ${SUSPSCAN_SCORE} + ${SUSPSCAN_MULTIPLIER}` 
+								unset SUSPSCAN_MULTIPLIER
+							else
+								SUSPSCAN_SCORE=`expr ${SUSPSCAN_SCORE} + 1`
 							fi
+						fi
 
-							SUSPSCAN_NUM=`expr ${SUSPSCAN_NUM} + 1`
-						done
+						SUSPSCAN_NUM=`expr ${SUSPSCAN_NUM} + 1`
+					done
 
-						if [ $SUSPSCAN_SCORE -ge $SUSPSCAN_THRESH ]; then
-							FOUNDDIRS="${FOUNDDIRS}
+					if [ $SUSPSCAN_SCORE -ge $SUSPSCAN_THRESH ]; then
+						FOUNDDIRS="${FOUNDDIRS}
 $SUSPSCAN_SCORE ${SUSPSCAN_ITEM}"
-						fi
+					fi
 
-						if [ $VERBOSE_LOGGING -eq 1 ]; then
-							display --to LOG --type PLAIN --log-indent 6 SUSPSCAN_FILE_CHECK "${SUSPSCAN_ITEM}" "$SUSPSCAN_SIZE" "${SUSPSCAN_TYPE}" "$SUSPSCAN_SCORE"
-						fi
+					if [ $VERBOSE_LOGGING -eq 1 ]; then
+						display --to LOG --type PLAIN --log-indent 6 SUSPSCAN_FILE_CHECK "${SUSPSCAN_ITEM}" "$SUSPSCAN_SCORE"
+					fi
 
-						unset SUSPSCAN_TERM
-						rm -f "${SUSPSCAN_TEMP}/suspscan.$$.strings" >/dev/null 2>&1
-					fi # test stringscan 
-				fi # test reg file
+					unset SUSPSCAN_TERM
+					rm -f ${FILENAME} >/dev/null 2>&1
+				fi # test stringscan 
 			done # find dir
 
 			if [ $VERBOSE_LOGGING -eq 1 -a $FOUND -eq 0 ]; then
